#!/bin/sh
# 执行前设置 githooks目录：$  git config core.hooksPath ./.githooks

# 进入项目根目录（以防Git Hook执行时路径错乱）
cd "$(git rev-parse --show-toplevel)/.githooks"

# 执行Python脚本
python3 ./__vault-format.py

# 检查执行是否成功
if [ $? -ne 0 ]; then
  echo "❌ Python脚本执行失败，已阻止Push。"
  exit 1
fi

# 成功就继续Push
exit 0
