name: Deploy to GitHub Pages

on:
  push:
    branches:
      - obsidian
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout obsidian branch
        uses: actions/checkout@v4
        with:
          ref: obsidian  # 确保checkout的是 obsidian 分支
          fetch-depth: 0  # 重要！否则 git push 时会出问题

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run your Python script
        run: |
          python .githooks/__vault-format.py

      - name: Switch to main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Copy changes from obsidian to main (excluding .githooks)
        run: |
          git checkout obsidian -- .
          rm -rf .githooks    
          rm -rf .github  
          rm -rf .obsidian

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "${{ github.event.head_commit.message }}" || echo "No changes to commit"
          git push origin main